Chris/style
GryphonRacingFSAE/Website pull request #3
Opened 2023-07-27 22:24 UTC by ChrisTienYenWalker

Modified Contact and Footer

Changes:

Footer: Added team information and logo and template for socials

Contact page: Added location, Google Maps embedded website and email contact

Proof of functionality (screenshot, logs, etc):
I showed you it, I haven't made changes since I showed it to you

Additional Notes
I didn't make any comments but I named everything well

Checklist
Your code builds clean without any errors or warnings
Code has been formatted (clang-format, cmake-format, black, prettier, rustfmt, etc)
Where possible, unit tests have been added
Code is well-commented & understood

2023-07-28 02:38 UTC, Nomalah requested changes
Can you remove the .nuxt directory and the app.vue file?
Add some screenshots as we don't have autodeploy for feature branches.
Run `npm run lint`

2023-07-28 02:38 UTC, Nomalah commented on src/assets/main.css
> +    --gryphon-black: #110f0fee;
This doesn't follow the university style guide, if you want to use a different color, make a different variable

2023-07-28 02:38 UTC, Nomalah commented on src/components/NavFooter.vue
> +                <NuxtLink to="/"><img src="../../public/media/GryphonBanner.svg" /></NuxtLink>
```suggestion
                <RouterLink to="/"><img src="/media/GryphonBanner.svg" /></RouterLink>
```
not using nuxt anymore

2023-07-28 02:38 UTC, Nomalah commented on src/views/ContactView.vue
> +    var(--_g) calc(200% - var(--_p,0%)) 100%;
What the buns is this?

2023-07-28 03:16 UTC, ChrisTienYenWalker commented
Your router redirect is not working

2023-07-29 02:29 UTC, Nomalah approved these changes

2023-07-29 03:09 UTC, merged